const collectionSeed = [
  ["sat1", "SAT Vocab #1", "#638dff"], ["sat2", "SAT Vocab #2", "#a36af3"], ["ielts", "IELTS Academic", "#51c88a"], ["difficult", "Difficult words", "#f0b867"], ["reading", "Reading practice", "#e579aa"],
].map(([id, name, color]) => ({ id, name, color }));

const wordSeed = [
  { w: "precocious", p: "/prɪˈkəʊʃəs/", pos: "adjective", d: "showing unusually early mental development or talent", tr: "рано развитый", e: "Her precocious interest in climate science changed the conversation at home.", r: ["advanced", "gifted", "mature"], c: ["sat1", "difficult"], s: "learning", m: 42, star: true, hard: true, rec: ["The museum hired a precocious intern who could already analyse conservation reports.", "What does precocious most likely mean here?", ["Developed beyond what is expected", "Careless with details", "Unwilling to learn", "Very difficult to notice"]], ctx: ["At dinner parties, guests were often surprised by the family's precocious seven-year-old, who asked detailed questions about economics and foreign policy.", "Why were the guests surprised?", ["The child had unusually advanced interests for their age", "The child refused to join the conversation", "The family hosted economists", "The questions had no purpose"]], fill: ["Although only eight, Mina gave a remarkably _____ presentation on renewable energy.", ["precocious", "conventional", "ambiguous", "reluctant"]] },
  { w: "abate", p: "/əˈbeɪt/", pos: "verb", d: "to become less intense or widespread", tr: "ослабевать", e: "The wind finally began to abate after midnight.", r: ["diminish", "subside", "ease"], c: ["sat1", "ielts"], s: "reviewing", m: 67, rec: ["Officials expected the traffic to abate once the concert ended.", "What does abate most likely mean here?", ["Become less severe", "Move to another place", "Cause a problem", "Happen suddenly"]], ctx: ["The criticism did not abate after the first apology, so the company released a detailed report.", "What does this tell us about the criticism?", ["It continued at a strong level", "It was a misunderstanding", "It had just begun", "It targeted the report"]], fill: ["The medicine helped the pain _____ within an hour.", ["abate", "accumulate", "clarify", "persist"]] },
  { w: "conventional", p: "/kənˈvenʃənəl/", pos: "adjective", d: "following what is commonly done, expected, or accepted", tr: "традиционный", e: "Rather than take a conventional route, the team tested a new method.", r: ["traditional", "customary", "standard"], c: ["sat1", "ielts", "difficult"], s: "mastered", m: 92, rec: ["The architect rejected conventional offices in favour of open community spaces.", "What does conventional most likely mean here?", ["Usual or traditional", "Expensive to maintain", "Built for many people", "Designed without a plan"]], ctx: ["The director chose a conventional ending because the audience expected the mystery to be resolved.", "Why did the director choose that ending?", ["It matched familiar audience expectations", "It made the story confusing", "It avoided resolving the mystery", "It was unpopular"]], fill: ["A handwritten note is less _____ now, but it can feel more personal.", ["conventional", "resilient", "meticulous", "candid"]] },
  { w: "meticulous", p: "/məˈtɪkjələs/", pos: "adjective", d: "showing great attention to detail; very careful and precise", tr: "тщательный", e: "The editor was meticulous about checking every source.", r: ["thorough", "precise", "scrupulous"], c: ["sat1", "reading"], s: "learning", m: 34, star: true, rec: ["Her meticulous notes included the date, source, and confidence level for each observation.", "What does meticulous most likely mean here?", ["Extremely careful about details", "Easy to understand", "Not based on evidence", "Finished quickly"]], ctx: ["Because the restoration was meticulous, visitors could not tell which sections had been repaired.", "What was the result of the restoration?", ["The repair blended in convincingly", "The repair was unfinished", "Visitors objected", "The value fell"]], fill: ["The researcher kept _____ records so others could repeat the experiment.", ["meticulous", "ambiguous", "conventional", "scarce"]] },
  { w: "ambiguous", p: "/æmˈbɪɡjuəs/", pos: "adjective", d: "having more than one possible meaning; unclear", tr: "неоднозначный", e: "The ambiguous announcement left employees unsure about the schedule.", r: ["unclear", "vague", "equivocal"], c: ["sat2", "ielts", "difficult"], s: "reviewing", m: 58, hard: true, rec: ["The law's ambiguous wording led two judges to different conclusions.", "What does ambiguous most likely mean here?", ["Open to more than one interpretation", "Required by law", "Clearly unfair", "Written long ago"]], ctx: ["When Lee replied, 'That could work,' the team could not tell whether he was enthusiastic or simply polite.", "Why was Lee's reply ambiguous?", ["It did not reveal his real support", "It explained the plan", "It rejected the idea", "It made the plan impossible"]], fill: ["The instructions were so _____ that two groups built different models.", ["ambiguous", "meticulous", "resilient", "candid"]] },
  { w: "candid", p: "/ˈkændɪd/", pos: "adjective", d: "truthful and direct, even when the truth may be uncomfortable", tr: "откровенный", e: "Her candid feedback made the next draft much stronger.", r: ["frank", "honest", "forthright"], c: ["sat2", "reading"], s: "new", m: 8, rec: ["In a candid interview, the athlete discussed mistakes that cost the match.", "What does candid most likely mean here?", ["Open and honest", "Highly emotional", "Carefully rehearsed", "Difficult to hear"]], ctx: ["The adviser was candid about the risks, but she also explained how the student could prepare.", "How did the adviser approach the conversation?", ["She spoke honestly while offering help", "She hid the risks", "She refused advice", "She focused on failures"]], fill: ["Please be _____ about whether the timeline is realistic.", ["candid", "precocious", "conventional", "scarce"]] },
  { w: "resilient", p: "/rɪˈzɪliənt/", pos: "adjective", d: "able to recover quickly from difficulty or change", tr: "устойчивый", e: "The resilient coastal plants survived another harsh winter.", r: ["adaptable", "tough", "durable"], c: ["ielts", "difficult"], s: "learning", m: 38, star: true, hard: true, rec: ["The small business proved resilient, finding new customers after the market changed.", "What does resilient most likely mean here?", ["Able to adapt and recover", "Unable to change", "Popular with customers", "Carefully planned"]], ctx: ["After losing its main supplier, the company reorganised production and met every order by Friday.", "Which quality does this show?", ["Resilience in the face of disruption", "A conventional preference", "Unclear communication", "An early talent"]], fill: ["A _____ community can recover more quickly after a natural disaster.", ["resilient", "ambiguous", "candid", "meticulous"]] },
  { w: "pragmatic", p: "/præɡˈmætɪk/", pos: "adjective", d: "focused on practical results rather than theories or ideals", tr: "прагматичный", e: "They took a pragmatic approach and repaired the bridge first.", r: ["practical", "realistic", "sensible"], c: ["ielts", "reading"], s: "mastered", m: 88, rec: ["Instead of debating the perfect design, the team made a pragmatic choice that fit the budget.", "What does pragmatic most likely mean here?", ["Guided by practical limits", "Interested in abstract ideas", "Unwilling to decide", "Concerned with tradition"]], ctx: ["The mayor supported the plan because it could be completed before winter, even though it was not the most ambitious option.", "Why was this decision pragmatic?", ["It prioritized a workable result", "It ignored all limits", "It chose the ideal plan", "It avoided deciding"]], fill: ["Given the budget, repairing the system was the most _____ choice.", ["pragmatic", "precocious", "ambiguous", "candid"]] },
  { w: "scarce", p: "/skeəs/", pos: "adjective", d: "available in small quantities; hard to find", tr: "дефицитный", e: "During the drought, clean water became scarce.", r: ["limited", "rare", "insufficient"], c: ["ielts", "difficult"], s: "new", m: 12, hard: true, rec: ["Affordable homes were scarce near the city centre.", "What does scarce most likely mean here?", ["In short supply", "Well designed", "Near the centre", "Easy to afford"]], ctx: ["Because rehearsal space was scarce, each band could reserve only two hours a week.", "What effect did scarcity have?", ["It limited time each band could use", "It improved comfort", "It gave extra time", "It stopped rehearsal"]], fill: ["When reliable data are _____, researchers must be cautious.", ["scarce", "meticulous", "conventional", "resilient"]] },
  { w: "advocate", p: "/ˈædvəkeɪt/", pos: "verb", d: "to publicly support or recommend an action or idea", tr: "выступать за", e: "Many scientists advocate protecting urban green spaces.", r: ["support", "promote", "endorse"], c: ["sat2", "ielts"], s: "reviewing", m: 61, rec: ["The doctor advocates shorter meetings so patients have more time for questions.", "What does advocates most likely mean here?", ["Publicly supports", "Studies carefully", "Strongly doubts", "Has completed"]], ctx: ["At the council meeting, Omar presented research and urged members to protect the wetland.", "What role is Omar taking?", ["He is advocating for protection", "He is describing a failure", "He is making it ambiguous", "He is seeking scarce data"]], fill: ["The report will _____ a gradual shift to renewable energy.", ["advocate", "abate", "accumulate", "conceal"]] },
  { w: "nuance", p: "/ˈnjuːɑːns/", pos: "noun", d: "a subtle difference in meaning, expression, or tone", tr: "оттенок значения", e: "The translator captured the nuance of the speaker's hesitation.", r: ["subtlety", "shade", "distinction"], c: ["sat2", "reading"], s: "learning", m: 46, rec: ["The actor changed the nuance of the line by pausing before the final word.", "What does nuance most likely mean here?", ["A small shade of meaning", "The main plot", "A factual error", "A loud sound"]], ctx: ["Both proposals support public transport, but one focuses on fares and the other late-night service.", "What is the nuance between them?", ["They prioritize different benefits", "They have no goal in common", "One rejects transport", "They are identical"]], fill: ["Knowing the cultural _____ helped her avoid an unintended insult.", ["nuance", "scarcity", "convention", "resilience"]] },
];

const app = { collections: structuredClone(collectionSeed), words: structuredClone(wordSeed).map((x) => ({ ...x, id: x.w, due: x.s !== "mastered" })), activeCollection: "all", activeStatus: "all", query: "", starredOnly: false, showAll: false, streak: 7, accuracy: 82 };
const root = document.querySelector("#overlay-root"), toast = document.querySelector("#toast");
let session, test, toastTimer;
const esc = (v = "") => String(v).replace(/[&<>'"]/g, (x) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" })[x]);
const coll = (id) => app.collections.find((x) => x.id === id);
const collectionWords = (id = app.activeCollection) => id === "all" ? app.words : app.words.filter((w) => w.c.includes(id));
const due = (w) => w.due || w.s === "reviewing";
const statusColor = (s) => ({ new: "#638dff", learning: "#a66bef", reviewing: "#eebc63", mastered: "#58ca89" })[s];
function save() { try { localStorage.setItem("lexora-state", JSON.stringify({ words: app.words, collections: app.collections, streak: app.streak, accuracy: app.accuracy })); } catch {} }
function load() { try { const x = JSON.parse(localStorage.getItem("lexora-state")); if (x?.words?.length) Object.assign(app, x); } catch {} }
function notice(s) { toast.textContent = s; toast.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove("show"), 2700); }

function renderCollections() {
  document.querySelector("#collection-nav").innerHTML = app.collections.map((c) => `<button data-action="collection" data-id="${c.id}" class="${app.activeCollection === c.id ? "active" : ""}" style="--collection-color:${c.color}"><i></i><span>${esc(c.name)}</span><b>${collectionWords(c.id).length}</b></button>`).join("");
  const filter = document.querySelector("#collection-filter"); filter.innerHTML = `<option value="all">All collections</option>${app.collections.map((c) => `<option value="${c.id}">${esc(c.name)}</option>`).join("")}`; filter.value = app.activeCollection;
}
function renderStats() {
  document.querySelector("#total-words").textContent = app.words.length;
  document.querySelector("#due-words").textContent = app.words.filter(due).length;
  document.querySelector("#nav-due").textContent = app.words.filter(due).length;
  document.querySelector("#mastered-words").textContent = app.words.filter((w) => w.s === "mastered").length;
  document.querySelector("#accuracy-value").textContent = `${app.accuracy}%`; document.querySelector("#streak-value").textContent = app.streak;
}
function matches() { const q = app.query.trim().toLowerCase(); return collectionWords().filter((w) => (app.activeStatus === "all" || w.s === app.activeStatus) && (!app.starredOnly || w.star) && (!q || `${w.w} ${w.d} ${w.r.join(" ")}`.toLowerCase().includes(q))); }
function renderWords() {
  const all = matches(), words = app.showAll ? all : all.slice(0, 8), list = document.querySelector("#word-list");
  document.querySelector("#word-bank-count").textContent = `${all.length} ${all.length === 1 ? "word" : "words"}`;
  const more = document.querySelector(".show-more"); more.style.visibility = all.length > 8 ? "visible" : "hidden"; more.innerHTML = app.showAll ? `Show fewer words <span>↑</span>` : `Show all ${all.length} words <span>→</span>`;
  list.innerHTML = words.length ? words.map((w, i) => `<article class="word-row" style="animation-delay:${i * 30}ms"><button class="word-open" data-action="edit" data-id="${w.id}"><span class="word-name"><strong>${esc(w.w)}</strong><small>${esc(w.pos)} · ${esc(w.d)}</small></span></button><span class="status ${w.s}">${w.s}</span><span class="mastery" style="--word-color:${statusColor(w.s)}"><i class="line"><i style="width:${w.m}%"></i></i><b>${w.m}%</b></span><button class="word-star ${w.star ? "starred" : ""}" data-action="star" data-id="${w.id}" aria-label="Star ${esc(w.w)}">${w.star ? "★" : "☆"}</button></article>`).join("") : `<div class="empty-words">No words match those filters. <button data-action="clear">Clear filters</button></div>`;
}
function renderProgress() {
  const id = app.activeCollection === "all" ? "sat1" : app.activeCollection, words = collectionWords(id), average = words.length ? Math.round(words.reduce((n, w) => n + w.m, 0) / words.length) : 0;
  document.querySelector("#progress-title").textContent = coll(id)?.name || "Your library"; document.querySelector("#collection-progress").textContent = `${average}%`; document.querySelector(".ring").style.background = `conic-gradient(var(--blue) 0 ${average}%, #29364e ${average}% 100%)`;
  document.querySelector("#collection-mastered").textContent = `${words.filter((w) => w.s === "mastered").length} / ${words.length}`;
  [["new", "new-count"], ["learning", "learning-count"], ["reviewing", "review-count"]].forEach(([s, el]) => document.querySelector(`#${el}`).textContent = words.filter((w) => w.s === s).length);
}
function renderCalendar() { const a = [0,0,1,2,0,3,1,0,2,0,0,1,2,3,1,0,0,2,3,0,1,2,0,3,1,2,3,0,1,0,2,3,0,1,0]; document.querySelector("#calendar").innerHTML = a.map((x, i) => `<span data-level="${x}" class="${i === 25 ? "today" : ""}"></span>`).join(""); }
function render() { renderCollections(); renderStats(); renderWords(); renderProgress(); renderCalendar(); }
function close() { root.innerHTML = ""; session = test = null; }

function taskVariants(w) {
  if (Array.isArray(w.tasks) && w.tasks.length) return w.tasks.filter((task) => task?.prompt && task?.options?.length >= 2);
  return [
    { type: "meaning", prompt: w.rec[0], question: w.rec[1], options: w.rec[2], correct: 0 },
    { type: "inference", prompt: w.ctx[0], question: w.ctx[1], options: w.ctx[2], correct: 0 },
    { type: "completion", prompt: w.fill[0], question: "Which word completes the sentence precisely?", options: w.fill[1], correct: 0 },
  ];
}
function shuffled(items) { return [...items].sort(() => Math.random() - .5); }
function startSession(kind = "daily") { const pool = collectionWords().filter((w) => kind !== "review" || due(w)); const queue = [...(pool.length ? pool : app.words)].sort((a,b) => Number(due(b)) - Number(due(a)) || Number(b.hard) - Number(a.hard)).slice(0,3); session = { kind, queue, taskOrder: queue.map((word) => shuffled(taskVariants(word)).slice(0, 3)), wi: 0, step: 0, picked: null, input: "", submitted: false, score: 0, scored: 0, improved: 0 }; sessionView(); }
function stepQuestion(w, step) { return step >= 1 && step <= 3 ? session.taskOrder[session.wi][step - 1] : null; }
function options(q) { return `<div class="answer-list">${q.options.map((x,i) => `<button class="answer-option ${session.picked === i ? "selected" : ""}" data-action="pick" data-id="${i}" ${session.submitted ? "disabled" : ""}><span class="option-letter">${String.fromCharCode(65+i)}</span>${esc(x)}</button>`).join("")}</div>`; }
function sessionView() {
  const w = session.queue[session.wi], q = stepQuestion(w, session.step), progress = Math.round((session.wi * 6 + session.step) / (session.queue.length * 6) * 100); let content;
  if (session.step === 0) content = `<span class="step-tag">01 · LEARN</span><h2>${esc(w.w)}</h2><span class="phonetic">${esc(w.p)}</span><p class="word-meta"><b>${esc(w.pos)}</b> · ${esc(w.tr)}</p><p class="definition">${esc(w.d)}.</p><div class="example-box">“${esc(w.e)}”</div><div class="related">RELATED <span>${w.r.map(esc).join("</span><span>")}</span></div><div class="session-actions"><button class="modal-cta" data-action="submit">I understand this word →</button></div>`;
  else if (session.step === 4) { const right = session.input.trim().toLowerCase() === w.w; content = `<span class="step-tag">05 · ACTIVE RECALL</span><h2>Can you retrieve it?</h2><p class="question-kicker">Type the word that means: <b>${esc(w.d)}</b>.</p><input class="recall-input" id="answer-input" value="${esc(session.input)}" placeholder="Type the word…" ${session.submitted ? "disabled" : ""}/><p class="hint">Pronunciation: ${esc(w.p)}</p>${session.submitted ? `<p class="feedback-line ${right ? "good" : "bad"}">${right ? "Exactly — you recalled it without a cue." : `The word was <b>${esc(w.w)}</b>. It will return sooner.`}</p>` : ""}<div class="session-actions"><button class="modal-cta" data-action="${session.submitted ? "advance" : "submit"}" ${!session.input.trim() ? "disabled" : ""}>${session.submitted ? "Continue →" : "Check recall"}</button></div>`; }
  else if (session.step === 5) content = `<span class="step-tag">06 · PERSONAL USE</span><h2>Make it yours.</h2><p class="question-kicker">Write one sentence using <b>${esc(w.w)}</b>. Use a situation you could genuinely encounter.</p><textarea class="use-textarea" id="answer-input" placeholder="Write your sentence…" ${session.submitted ? "disabled" : ""}>${esc(session.input)}</textarea><p class="hint">Your sentence is private to this workspace.</p>${session.submitted ? `<p class="feedback-line good">Nice. Personal examples create a stronger memory path.</p>` : ""}<div class="session-actions"><button class="modal-cta green" data-action="${session.submitted ? "advance" : "submit"}" ${session.input.trim().length < 12 ? "disabled" : ""}>${session.submitted ? "Finish word →" : "Save my example"}</button></div>`;
  else { const meta = { meaning: ["02 · MEANING IN CONTEXT", "Spot the meaning."], inference: ["03 · CONTEXTUAL INFERENCE", "Read the situation."], completion: ["04 · SENTENCE COMPLETION", "Choose the precise word."] }[q.type] || ["02 · WORD IN CONTEXT", "Reason from the passage."]; const right = session.picked === q.correct; content = `<span class="step-tag">${meta[0]}</span><h2>${meta[1]}</h2><p class="question-kicker">${esc(q.prompt)}</p><p class="question-kicker"><b>${esc(q.question || "Which answer is best supported by the text?")}</b></p>${options(q)}${session.submitted ? `<p class="feedback-line ${right ? "good" : "bad"}">${right ? "Correct. You caught the intended meaning." : `${esc(w.w)} means ${esc(w.d)}.`}</p>` : ""}<div class="session-actions"><button class="modal-cta" data-action="${session.submitted ? "advance" : "submit"}" ${session.picked === null ? "disabled" : ""}>${session.submitted ? "Continue →" : "Check answer"}</button></div>`; }
  root.innerHTML = `<div class="overlay" role="dialog" aria-modal="true"><section class="modal session-modal"><div class="session-top"><span class="session-label">${session.kind === "review" ? "REVIEW QUEUE" : "DAILY SESSION"} · ${session.wi+1} OF ${session.queue.length} WORDS</span><button class="icon-button session-close" data-action="close" aria-label="Close">×</button></div><div class="session-progress"><i style="width:${progress}%"></i></div><div class="session-body">${content}</div></section></div>`;
  const input = document.querySelector("#answer-input"); if (input && !session.submitted) { input.focus(); input.addEventListener("input", () => { session.input = input.value; sessionView(); }); }
}
function submit() { if (session.step === 0) return advance(); const w = session.queue[session.wi]; let good = true; if (session.step >= 1 && session.step <= 3) good = session.picked === stepQuestion(w, session.step).correct; if (session.step === 4) good = session.input.trim().toLowerCase() === w.w; if (session.step === 5) good = session.input.trim().length >= 12; if (session.step) { session.scored++; if (good) session.score++; } session.submitted = true; sessionView(); }
function advance() { const w = session.queue[session.wi]; if (session.step === 5) { const gain = Math.max(4, Math.round(session.score / Math.max(session.scored, 1) * 9)); w.m = Math.min(100, w.m + gain); w.due = false; w.s = w.m >= 84 ? "mastered" : w.m >= 52 ? "reviewing" : "learning"; session.improved++; } if (session.step === 5 && session.wi === session.queue.length - 1) return sessionResult(); if (session.step === 5) { session.wi++; session.step = 0; } else session.step++; Object.assign(session, { picked: null, input: "", submitted: false }); sessionView(); }
function sessionResult() { const accuracy = Math.round(session.score / Math.max(session.scored, 1) * 100); app.accuracy = Math.round((app.accuracy*3 + accuracy)/4); app.streak++; save(); render(); root.innerHTML = `<div class="overlay" role="dialog" aria-modal="true"><section class="modal"><div class="result"><div class="result-mark">✓</div><p class="eyebrow">SESSION COMPLETE</p><h2>Meaning made memorable.</h2><p>You moved through every layer of understanding — not just the definition.</p><div class="result-grid"><div><strong>${accuracy}%</strong><span>session accuracy</span></div><div><strong>${session.queue.length}</strong><span>words learned</span></div><div><strong>${session.improved}</strong><span>words improved</span></div></div><p class="next-review">Next review: <b>tomorrow at 09:00</b> · difficult answers return sooner.</p><button class="modal-cta green" data-action="close">Back to my workspace</button></div></section></div>`; }

function testConfig() { test = { collection: app.collections[0].id }; root.innerHTML = `<div class="overlay" role="dialog" aria-modal="true"><section class="modal"><button class="icon-button modal-close" data-action="close">×</button><div class="modal-intro"><p class="eyebrow">TEST LAB</p><h2>Build a useful test.</h2><p>Answers stay hidden until you finish. Choose a focused set, then see explanations together.</p><label class="field-label">VOCABULARY COLLECTION</label><div class="collection-choice" id="test-collections">${app.collections.slice(0,4).map((c,i) => `<button class="choice ${i===0?"selected":""}" data-action="test-collection" data-id="${c.id}"><strong>${esc(c.name)}</strong><span>${collectionWords(c.id).length} words available</span></button>`).join("")}</div><div class="config-grid"><label><span class="field-label">QUESTIONS</span><select id="test-count"><option value="5">5 questions</option><option value="8">8 questions</option><option value="10">10 questions</option></select></label><label><span class="field-label">DIFFICULTY</span><select><option>Balanced</option><option>Challenging</option><option>Mixed review</option></select></label></div><span class="field-label">QUESTION TYPES</span><div class="check-grid"><label class="check-item"><input type="checkbox" checked> Definition</label><label class="check-item"><input type="checkbox" checked> Meaning in context</label><label class="check-item"><input type="checkbox" checked> Contextual inference</label><label class="check-item"><input type="checkbox" checked> Sentence completion</label><label class="check-item"><input type="checkbox"> Typing the word</label><label class="check-item"><input type="checkbox"> Synonym / antonym</label></div><div class="modal-footer"><label class="check-item"><input id="hard-only" type="checkbox"> Starred / difficult only</label><button class="modal-cta purple" data-action="begin-test">Start test →</button></div></div></section></div>`; }
function makeQuestion(w, i) { const imported = taskVariants(w)[i % taskVariants(w).length]; const fallback = i % 3 === 0 ? ["Which definition best matches this word?", [w.d, ...app.words.filter((x) => x.id !== w.id).slice(0,3).map((x) => x.d)], 0] : [imported.prompt, imported.options, imported.correct]; const options = fallback[1].map((t,n)=>({t,right:n===fallback[2]})).sort(()=>Math.random()-.5); return { w, prompt: fallback[0], options, correct: options.findIndex((o)=>o.right) }; }
function beginTest() { let pool = collectionWords(test.collection); if (document.querySelector("#hard-only").checked) pool = pool.filter((w)=>w.star||w.hard); if (pool.length < 2) pool = app.words; const count = +document.querySelector("#test-count").value, ordered = [...pool].sort(()=>Math.random()-.5); test = { ...test, qs: Array.from({length:count},(_,i)=>makeQuestion(ordered[i%ordered.length],i)), i:0, selected:null, answers:[] }; testView(); }
function testView() { const q=test.qs[test.i], p=Math.round(test.i/test.qs.length*100); root.innerHTML=`<div class="overlay" role="dialog" aria-modal="true"><section class="modal session-modal"><div class="session-top"><span class="session-label">VOCAB TEST · QUESTION ${test.i+1} OF ${test.qs.length}</span><button class="icon-button session-close" data-action="close">×</button></div><div class="session-progress"><i style="width:${p}%;background:var(--purple)"></i></div><div class="session-body"><span class="step-tag" style="color:#d2b7ff;background:rgba(147,97,242,.12)">ANSWER NOW · REVIEW LATER</span><h2>Choose the best answer.</h2><p class="question-kicker">${esc(q.prompt)}</p><div class="answer-list">${q.options.map((o,i)=>`<button class="answer-option ${test.selected===i?"selected":""}" data-action="test-answer" data-id="${i}"><span class="option-letter">${String.fromCharCode(65+i)}</span>${esc(o.t)}</button>`).join("")}</div><div class="session-actions"><button class="modal-cta purple" data-action="next-test" ${test.selected===null?"disabled":""}>${test.i+1===test.qs.length?"Finish test →":"Next question →"}</button></div></div></section></div>`; }
function nextTest() { test.answers.push(test.selected); if(test.i===test.qs.length-1)return testResult(); test.i++;test.selected=null;testView(); }
function testResult() { const correct=test.qs.filter((q,i)=>q.correct===test.answers[i]).length, percent=Math.round(correct/test.qs.length*100); app.accuracy=Math.round((app.accuracy*2+percent)/3);save();render(); const reviews=test.qs.map((q,i)=>`<div class="test-review ${q.correct===test.answers[i]?"good":"bad"}"><span>${q.correct===test.answers[i]?"✓":"×"}</span><p><b>${esc(q.w.w)}</b> · “${esc(q.w.w)}” means ${esc(q.w.d)}.<small>${q.correct===test.answers[i]?"Correct":`Your answer: ${esc(q.options[test.answers[i]].t)}`}</small></p></div>`).join(""); root.innerHTML=`<div class="overlay" role="dialog" aria-modal="true"><section class="modal"><button class="icon-button modal-close" data-action="close">×</button><div class="modal-intro test-results"><p class="eyebrow">TEST COMPLETE</p><h2>${percent>=80?"Strong work.":"Useful signal."}</h2><p>${correct} of ${test.qs.length} correct. The answers below explain every word in context.</p><div class="result-grid"><div><strong>${percent}%</strong><span>accuracy</span></div><div><strong>${correct}</strong><span>correct</span></div><div><strong>${test.qs.length-correct}</strong><span>to revisit</span></div></div><div class="test-review-list">${reviews}</div><div class="modal-footer"><span class="subtle-note">Incorrect answers are prioritised in review.</span><button class="modal-cta purple" data-action="close">Done</button></div></div></section></div>`; }

function collectionModal() { root.innerHTML=`<div class="overlay" role="dialog" aria-modal="true"><section class="modal"><button class="icon-button modal-close" data-action="close">×</button><div class="modal-intro"><p class="eyebrow">NEW COLLECTION</p><h2>Give a set of words a home.</h2><p>Collections can overlap, so a word can appear in both SAT and IELTS study plans.</p><label class="field-label">COLLECTION NAME</label><input id="collection-name" placeholder="e.g. Words from October reading" maxlength="38" autofocus><label class="field-label">ACCENT</label><div class="color-choice"><button class="color-dot selected" data-action="color" data-id="#638dff" style="--dot:#638dff"></button><button class="color-dot" data-action="color" data-id="#a36af3" style="--dot:#a36af3"></button><button class="color-dot" data-action="color" data-id="#51c88a" style="--dot:#51c88a"></button><button class="color-dot" data-action="color" data-id="#e579aa" style="--dot:#e579aa"></button></div><div class="modal-footer"><span class="subtle-note">You can add words next.</span><button class="modal-cta" data-action="save-collection">Create collection</button></div></div></section></div>`; }
function saveCollection() { const input=document.querySelector("#collection-name"),name=input.value.trim(); if(!name)return notice("Give the collection a name first."); const color=document.querySelector(".color-dot.selected")?.dataset.id||"#638dff",id=`collection-${Date.now()}`;app.collections.push({id,name,color});app.activeCollection=id;save();render();close();notice(`“${name}” is ready for words.`); }
function wordModal(id) { const w=app.words.find((x)=>x.id===id), editing=!!w; root.innerHTML=`<div class="overlay" role="dialog" aria-modal="true"><section class="modal"><button class="icon-button modal-close" data-action="close">×</button><div class="modal-intro"><p class="eyebrow">${editing?"WORD DETAILS":"ADD A WORD"}</p><h2>${editing?esc(w.w):"Build your library."}</h2><div class="config-grid"><label><span class="field-label">WORD</span><input id="editor-word" value="${esc(w?.w||"")}" placeholder="e.g. tenacious"></label><label><span class="field-label">PART OF SPEECH</span><select id="editor-pos">${["adjective","noun","verb","adverb"].map((x)=>`<option ${w?.pos===x?"selected":""}>${x}</option>`).join("")}</select></label></div><label><span class="field-label">SIMPLE DEFINITION</span><input id="editor-definition" value="${esc(w?.d||"")}" placeholder="What does it mean in plain English?"></label><label><span class="field-label">EXAMPLE SENTENCE</span><textarea class="use-textarea" id="editor-example" placeholder="Use it in a real situation…">${esc(w?.e||"")}</textarea></label><span class="field-label">IN COLLECTIONS</span><div class="check-grid">${app.collections.map((c)=>`<label class="check-item"><input type="checkbox" value="${c.id}" ${w?.c.includes(c.id)?"checked":""}> ${esc(c.name)}</label>`).join("")}</div><div class="modal-footer">${editing?`<button class="danger-button" data-action="delete" data-id="${w.id}">Remove word</button>`:`<span class="subtle-note">You can edit details later.</span>`}<button class="modal-cta" data-action="save-word" data-id="${w?.id||""}">${editing?"Save changes":"Add word"}</button></div></div></section></div>`; }
function saveWord(id) { const w=document.querySelector("#editor-word").value.trim().toLowerCase(),d=document.querySelector("#editor-definition").value.trim(),e=document.querySelector("#editor-example").value.trim(),pos=document.querySelector("#editor-pos").value,c=[...document.querySelectorAll(".check-grid input:checked")].map(x=>x.value); if(!w||!d||!c.length)return notice("Add a word, its meaning, and at least one collection."); const data={w,d,e,pos,c}; if(id)Object.assign(app.words.find(x=>x.id===id),data);else app.words.unshift({id:`${w}-${Date.now()}`,...data,p:"/add pronunciation/",tr:"",r:[],s:"new",m:0,star:false,hard:false,due:true,rec:[e||`The word ${w} appeared in the article.`,`What does ${w} most likely mean?`,[d,"A familiar routine","A sudden change","A source of doubt"]],ctx:[e||`The writer used ${w} in a discussion.`,`What should a reader do next?`,["Use surrounding context","Ignore the word","Assume no effect","Choose randomly"]],fill:[`The writer chose the word _____.`,[w,"ordinary","unclear","limited"]]});save();render();close();notice(`“${w}” ${id?"was updated":"was added to your library"}.`); }

document.addEventListener("click",(e)=>{const t=e.target.closest("[data-action]");if(!t)return;const a=t.dataset.action,id=t.dataset.id;if(a==="close")close();if(a==="start")startSession();if(a==="review")startSession("review");if(a==="test")testConfig();if(a==="collection"){app.activeCollection=id;app.showAll=false;render()}if(a==="star-filter"){app.starredOnly=!app.starredOnly;t.setAttribute("aria-pressed",app.starredOnly);renderWords()}if(a==="star"){const w=app.words.find(x=>x.id===id);w.star=!w.star;save();renderWords()}if(a==="clear"){app.activeStatus="all";app.starredOnly=false;app.query="";document.querySelector("#word-search").value="";document.querySelectorAll(".filter-tab").forEach(x=>x.classList.toggle("active",x.dataset.status==="all"));renderWords()}if(a==="show-more"){app.showAll=!app.showAll;renderWords()}if(a==="pick"){session.picked=+id;sessionView()}if(a==="submit")submit();if(a==="advance")advance();if(a==="test-collection"){test.collection=id;document.querySelectorAll("#test-collections .choice").forEach(x=>x.classList.toggle("selected",x===t))}if(a==="begin-test")beginTest();if(a==="test-answer"){test.selected=+id;testView()}if(a==="next-test")nextTest();if(a==="new-collection")collectionModal();if(a==="color"){document.querySelectorAll(".color-dot").forEach(x=>x.classList.toggle("selected",x===t))}if(a==="save-collection")saveCollection();if(a==="add-word")wordModal();if(a==="edit")wordModal(id);if(a==="save-word")saveWord(id);if(a==="delete"){const w=app.words.find(x=>x.id===id);app.words=app.words.filter(x=>x.id!==id);save();render();close();notice(`Removed “${w.w}”.`)}if(a==="profile")notice("This personal workspace is saved separately in this browser.");if(a==="focus"){document.body.classList.toggle("focus-mode");notice(document.body.classList.contains("focus-mode")?"Focus mode on — distractions dimmed.":"Focus mode off.")}if(a==="menu")document.querySelector(".sidebar").classList.toggle("open")});
document.addEventListener("click",(e)=>{const t=e.target.closest(".filter-tab");if(!t)return;app.activeStatus=t.dataset.status;app.showAll=false;document.querySelectorAll(".filter-tab").forEach(x=>x.classList.toggle("active",x===t));renderWords()});
document.querySelector("#word-search").addEventListener("input",(e)=>{app.query=e.target.value;app.showAll=false;renderWords()});
document.querySelector("#collection-filter").addEventListener("change",(e)=>{app.activeCollection=e.target.value;app.showAll=false;render()});
document.addEventListener("keydown",(e)=>{if(e.key==="Escape"&&root.innerHTML)close()});
load();render();
